### ISSUE TITLE
Configure tls automatically if valid certificate path provided

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/ansible-filebeat#1]
Instead of just checking for the existence of the `filebeat_tls_certificate` variable, also check for the existence of the certificate at the path specified, i.e:

```yaml
- name: verify specified tls certificate
  stat: path={{ filebeat_tls_certificate }}
  register=check_certificate

- name: set whether to use tls
  set_fact: use_tls=yes
  when: check_certificate.stat.exists
```
